# Generated by Django 3.2 on 2024-07-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0008_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_file', models.ImageField(upload_to='slides/')),
                ('slider_title', models.CharField(max_length=255)),
            ],
        ),
    ]
