# Generated by Django 3.2 on 2024-07-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0009_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='slider_file',
            field=models.ImageField(upload_to='slider_images/'),
        ),
    ]
