# Generated by Django 3.2 on 2024-07-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0010_alter_slide_slider_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='slider_file',
            field=models.ImageField(blank=True, null=True, upload_to='slider_images/'),
        ),
    ]
