# Generated by Django 3.2 on 2024-07-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0016_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
