# Generated by Django 3.2 on 2024-07-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0020_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
